export default {
    products: [{
        _id:'1',
        name: 'Slim Shirts',
        category: 'Shirts',
        image: '/images/d1.jpg',
        price: '100.000',
        brand: 'Nike',
        rating: 4.5,
        numReviews: 10,
        countInStock : 0,
    },
    {
        _id:'2',
        name: 'Fit Shirts',
        category: 'Shirts',
        image: '/images/d1.jpg',
        price: '500.000',
        brand: 'Nike',
        rating: 4.5,
        numReviews: 10,
        countInStock : 9,
    },
    {
        _id:'3',
        name: 'Short Pants',
        category: 'Pants',
        image: '/images/d1.jpg',
        price: '100.000',
        brand: 'Nike',
        rating: 4.5,
        numReviews: 10,
        countInStock : 0,
    },
    {
        _id:'4',
        name: 'Long Pants',
        category: 'Pants',
        image: '/images/d1.jpg',
        price: '200.000',
        brand: 'Nike',
        rating: 4.5,
        numReviews: 10,
        countInStock : 6,
    },
    ]
}